name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  cypress-tests-EnvioEmailTesteDFe:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run end-to-end tests on tablet viewpr 🧪
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:envioEmailTeste
      - name: Upload a Build Artifact
        if: always()
        uses: actions/upload-artifact@v2.2.4
        with:
          path: cypress/videos