name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  cypress-tests-EnvioEmailTesteDFe:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run end-to-end tests on tablet viewport 🧪
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:envioEmailTeste